#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

printf "# Header\nText \$f(x)=x^2\$" |
pandoc -f markdown -t html --standalone --self-contained

printf "# Header\nText \$f(x)=x^2\$" |
pandoc -f markdown -t html --standalone --self-contained |
pyppdf -o "$HOME/doc.pdf" --goto temp
if [[ -f "$HOME/doc.pdf" ]]; then
    echo "$HOME/doc.pdf exists."
else
    echo -e "$HOME/doc.pdf does not exist."
    exit 1
fi
